[package]
name = "lesson_planner"
version = "0.1.0"
edition = "2021"

[dependencies]
askama =  "0.11.1"
axum = "0.6.6"
# axum-extra = { version = "0.4.2", features = ["spa"] }
hyper = { version = "0.14.24", features = ["full"] }
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
